# Generated by Django 5.2.5 on 2026-03-22 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_portfolio_is_default_alter_portfolio_allocation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_params', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('horizon_days', models.IntegerField(default=126)),
                ('analysis_mode', models.CharField(choices=[('single', 'Single Strategy Analysis'), ('multi', 'Multi-Strategy Analysis')], default='single', max_length=16)),
                ('prior_mode', models.CharField(choices=[('universe', 'Universe Prior'), ('golden_cross', 'Golden Cross Prior')], default='universe', max_length=32)),
                ('prior_value', models.FloatField()),
                ('posterior_value', models.FloatField(blank=True, null=True)),
                ('benchmark', models.CharField(default='SPY', max_length=16)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=16)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prior_probability', models.FloatField()),
                ('posterior_probability', models.FloatField()),
                ('evidence_json', models.JSONField(default=dict)),
                ('explanation_json', models.JSONField(default=dict)),
                ('backtest_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_snapshot', to='my_app.backtestrun')),
            ],
        ),
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_slug', models.CharField(max_length=64)),
                ('sequence_index', models.PositiveIntegerField(default=1)),
                ('entry_date', models.DateField()),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('shares', models.FloatField(default=0)),
                ('pnl', models.FloatField(blank=True, null=True)),
                ('return_pct', models.FloatField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=16)),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='my_app.backtestrun')),
            ],
            options={
                'ordering': ['entry_date', 'sequence_index'],
            },
        ),
        migrations.CreateModel(
            name='StrategyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_index', models.PositiveIntegerField(default=1)),
                ('params', models.JSONField(default=dict)),
                ('signal_active', models.BooleanField(default=False)),
                ('used_as_prior', models.BooleanField(default=False)),
                ('strength_score', models.FloatField(blank=True, null=True)),
                ('likelihood_ratio', models.FloatField(blank=True, null=True)),
                ('weighted_log_lr', models.FloatField(blank=True, null=True)),
                ('posterior_after', models.FloatField(blank=True, null=True)),
                ('metrics', models.JSONField(default=dict)),
                ('evidence_json', models.JSONField(blank=True, default=dict)),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_runs', to='my_app.backtestrun')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.strategydefinition')),
            ],
            options={
                'ordering': ['sequence_index'],
                'constraints': [models.UniqueConstraint(fields=('backtest_run', 'sequence_index'), name='unique_backtest_sequence_index')],
            },
        ),
    ]
